#!/bin/sh
# (c) Positive Technologies 2012
# Author: Timur Gilmullin
#
# Your must install Power Shell on Win. Then put this file into your .git/hooks/ directory.
#
# Setup path to commands for execute.
#
# Path to local PowerShell:
shell="C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy RemoteSigned -Command"
# Command to run unittest:
testRun="C:/ProgramData/Anaconda3/python.exe C:/Users/NaWashington/PycharmProjects/14_pre_commit_hook/tests.py"
# Running pre-commit and gets exit-code:
runString=$shell' '$testRun
exec $runString
exitCode=$?
echo "Exit-code of unittest is:"
echo $exitCode
if [ x"$exitCode" == x"0" ]
then
	exit 0
else
	echo "Not all unit-tests passed! Commit canceled!"
	exit 1
fi